Support Older Browsers
CompositionalIT/safe-stack-docs pull request #24
Opened 2020-08-24 12:08 UTC by functionalprogrammer

2020-08-24 12:52 UTC, Ryan-Palmer-CIT commented on docs/recipes/webpack/support-older-browsers.md
> +Simply put, a *polyfill* is a block of code that implements a feature on web browsers that do not support that feature. All we need to use polyfills where necessary is to tell [Babel](https://babeljs
You could change the bold polyfill at the start of this paragraph with a link, then you could remove the 'find out more here' bit at the end.

2020-08-24 16:03 UTC, theprash commented on docs/recipes/webpack/support-older-browsers.md
> +Simply put, a [polyfill](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill#:~:text=A%20polyfill%20is%20a%20piece,do%20not%20natively%20support%20it) is a block of code that implements a feat
This URL has some unnecessary stuff added from `#` onwards. I think Chrome adds this onto URLs from Google searches so that text is highlighted on the page. You can get rid of it.

2020-08-26 09:46 UTC, theprash requested changes

2020-08-26 09:46 UTC, theprash commented on docs/recipes/webpack/support-older-browsers.md
> +Your `webpack.config.js` file should look like [this](https://gist.github.com/functionalprogrammer/deb9ed69e9c0040635cdca6f0ce35ae2) in the end.
This file is now out of date with my latest change to move npm/webpack files to the root dir. It will be easy for it to go out of sync again so maybe it's best not to include it at all.

2020-08-26 17:04 UTC, merged